language: node_js
deploy:
  provider: heroku
  buildpack: https://github.com/ddollar/heroku-buildpack-multi.git
  api_key:
    secure: hhQPnDeNFR+V6eE0NHqExjPLpWoW/5cGe/FuL/uC4X2OPyAiTSD4Ts0/NY+VFPjK9469U02PJ0gxrbr5TrU3oTp0tl1QW9Ygf7Gzn3xeMGGVvbJHnch70YMnTl55XZj8AxIYk/OVjiZf7wS6ah8Y7+WXgv43ea547BQoog7h78p4abySN+IpS7AyfCu9MGq+J5fGlLBJo1oQFVnevCPgYq8Yfobfj7OOYEdioFnJgWtOGRKUUT3+5yFx77pyl8ceVLPk3ACslIJB4tsELnvBla1i8KcEKKFhaCxxCRo6q5oey7wSsNA+tTmQlYMcPx0RK8q4MHOIsEe+NfWfrv5B5FxO4N98mdElkogvhGRWvE00vDlBzPwBVAbmDoHfX10U7fVC9FaHnkkYBMYJW0Xsav4bWmd1RmtPb+RIr7IPD7Rweu4zMD191V72gIID4P9+XIoALjv8kEEfRicMxaC6kwqdzaMnv3Mxh/Jxf9caWXU+H9GfRW5FufV+Szfn77XRqL0db3urErp73gecixmer0FCRlmhCMcdwaNIqsFRpslrgy96PIvRG7DP/2Rmpo8R7h8lQFeOo9JpMBiJWRuK50yRRNmbgTFOcb0Dj5zhkwVCnYMs72UdyEkcVrZRWo96+Nk1VSLEyX8BG9GDD418TU71tPqt/HH1X5JSOQsSQkg=
  app: nginx-node-example
  skip_cleanup: true
